spring:
  config:
    import:
      - /Users/codejuzi/Documents/CodeWorkSpace/Project/Ju-Connect/config/gateway_conf.properties
  cloud:
    gateway:
      routes:
        - id: api_route
          # 模拟接口的地址
          uri: http://localhost:8200
          predicates:
            - Path=/api/**
          filters:
            # 模拟接口层可以做校验，校验请求头中是否包含gateway-key: codejuzi12138
            - AddRequestHeader=gateway-key, codejuzi12138