server:
  port: 10000
  servlet:
    context-path: /api

spring:
  application:
    name: ju-gateway-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.101:8848

# 开启日志
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
