server:
  port: 10000
  servlet:
    context-path: /api

spring:
  application:
    name: ju-connect-gateway
  profiles:
    active: dev

# 开启日志
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace