spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://localhost:3306/ju_connect             # 数据库连接URL
    username: codejuzi                                      # 数据库用户名
    password: codejuzi                                      # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver             # 数据库驱动类名
    type: com.alibaba.druid.pool.DruidDataSource            # 指定使用Druid数据源
    druid:
      max-active: 20                                        # 连接池最大并发连接数
      initial-size: 1                                       # 连接池初始化连接数
      max-wait: 60000                                       # 获取连接最大等待时间，单位毫秒
#      filters: stat,wall,log4j                               # 连接池过滤器配置，可选
#      minIdle: 1                                             # 连接池最小空闲连接数
#      timeBetweenEvictionRunsMillis: 60000                   # 定时检查空闲连接间隔时间，单位毫秒
#      minEvictableIdleTimeMillis: 300000                     # 连接在池中最小生存的时间，单位毫秒
#      validationQuery: SELECT 1 FROM DUAL                    # 检查连接是否有效的SQL语句
#      testWhileIdle: true                                    # 空闲时是否进行连接检查
#      testOnBorrow: false                                    # 取出连接时是否进行连接检查
#      testOnReturn: false                                    # 归还连接时是否进行连接检查
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mybatis:
  mapper-locations: classpath:/mapper/*.xml

dubbo:
  registry:
    id: nacos-registry
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: -1
  scan:
    base-packages: com.juzi.web.rpc
